pipeline {
    agent any
    environment {
        registry = 'swatkiev/docker-test'
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/swatkiev/dockertasks.git'
            }
        }
        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build(registry + ":$BUILD_NUMBER","./zadanie1_2")
		}
            }
        }
        stage('Deploy Image') {
            steps {
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Remove Unused docker image') {
            steps {
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}
